---
abstract: 'A base class for Catalyst MVC components'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Class::Null: 1.09
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Usul
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  CatalystX::Usul:
    file: lib/CatalystX/Usul.pm
    version: v0.8.1321
  CatalystX::Usul::Action:
    file: lib/CatalystX/Usul/Action.pm
    version: v0.8.1319
  CatalystX::Usul::Admin:
    file: lib/CatalystX/Usul/Admin.pm
    version: v0.8.1320
  CatalystX::Usul::Authentication:
    file: lib/CatalystX/Usul/Authentication.pm
    version: v0.8.1319
  CatalystX::Usul::CLI:
    file: lib/CatalystX/Usul/CLI.pm
    version: v0.8.1320
  CatalystX::Usul::Config:
    file: lib/CatalystX/Usul/Config.pm
    version: v0.8.1319
  CatalystX::Usul::Constants:
    file: lib/CatalystX/Usul/Constants.pm
    version: v0.8.1320
  CatalystX::Usul::Constraints:
    file: lib/CatalystX/Usul/Constraints.pm
    version: v0.8.1320
  CatalystX::Usul::Controller:
    file: lib/CatalystX/Usul/Controller.pm
    version: v0.8.1320
  CatalystX::Usul::Controller::Admin:
    file: lib/CatalystX/Usul/Controller/Admin.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::Backup:
    file: lib/CatalystX/Usul/Controller/Admin/Backup.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::Config:
    file: lib/CatalystX/Usul/Controller/Admin/Config.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::Locks:
    file: lib/CatalystX/Usul/Controller/Admin/Locks.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::Navigation:
    file: lib/CatalystX/Usul/Controller/Admin/Navigation.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::Processes:
    file: lib/CatalystX/Usul/Controller/Admin/Processes.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::RoleManager:
    file: lib/CatalystX/Usul/Controller/Admin/RoleManager.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Admin::UserManager:
    file: lib/CatalystX/Usul/Controller/Admin/UserManager.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Entrance:
    file: lib/CatalystX/Usul/Controller/Entrance.pm
    version: v0.8.1319
  CatalystX::Usul::Controller::Root:
    file: lib/CatalystX/Usul/Controller/Root.pm
    version: v0.8.1319
  CatalystX::Usul::FileSystem:
    file: lib/CatalystX/Usul/FileSystem.pm
    version: v0.8.1320
  CatalystX::Usul::Functions:
    file: lib/CatalystX/Usul/Functions.pm
    version: v0.8.1305
  CatalystX::Usul::InflateSymbols:
    file: lib/CatalystX/Usul/InflateSymbols.pm
    version: v0.8.1319
  CatalystX::Usul::Model:
    file: lib/CatalystX/Usul/Model.pm
    version: v0.8.1320
  CatalystX::Usul::Model::Config:
    file: lib/CatalystX/Usul/Model/Config.pm
    version: v0.8.1320
  CatalystX::Usul::Model::Config::Buttons:
    file: lib/CatalystX/Usul/Model/Config/Buttons.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Credentials:
    file: lib/CatalystX/Usul/Model/Config/Credentials.pm
    version: v0.8.1320
  CatalystX::Usul::Model::Config::Fields:
    file: lib/CatalystX/Usul/Model/Config/Fields.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Globals:
    file: lib/CatalystX/Usul/Model/Config/Globals.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Keys:
    file: lib/CatalystX/Usul/Model/Config/Keys.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Levels:
    file: lib/CatalystX/Usul/Model/Config/Levels.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Messages:
    file: lib/CatalystX/Usul/Model/Config/Messages.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Config::Rooms:
    file: lib/CatalystX/Usul/Model/Config/Rooms.pm
    version: v0.8.1319
  CatalystX::Usul::Model::FileSystem:
    file: lib/CatalystX/Usul/Model/FileSystem.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Help:
    file: lib/CatalystX/Usul/Model/Help.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Imager:
    file: lib/CatalystX/Usul/Model/Imager.pm
    version: v0.8.1320
  CatalystX::Usul::Model::MailAliases:
    file: lib/CatalystX/Usul/Model/MailAliases.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Navigation:
    file: lib/CatalystX/Usul/Model/Navigation.pm
    version: v0.8.1320
  CatalystX::Usul::Model::Process:
    file: lib/CatalystX/Usul/Model/Process.pm
    version: v0.8.1320
  CatalystX::Usul::Model::Roles:
    file: lib/CatalystX/Usul/Model/Roles.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Schema:
    file: lib/CatalystX/Usul/Model/Schema.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Session:
    file: lib/CatalystX/Usul/Model/Session.pm
    version: v0.8.1320
  CatalystX::Usul::Model::TapeBackup:
    file: lib/CatalystX/Usul/Model/TapeBackup.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Templates:
    file: lib/CatalystX/Usul/Model/Templates.pm
    version: v0.8.1320
  CatalystX::Usul::Model::UserProfiles:
    file: lib/CatalystX/Usul/Model/UserProfiles.pm
    version: v0.8.1319
  CatalystX::Usul::Model::Users:
    file: lib/CatalystX/Usul/Model/Users.pm
    version: v0.8.1320
  CatalystX::Usul::Moose:
    file: lib/CatalystX/Usul/Moose.pm
    version: v0.8.1319
  CatalystX::Usul::ProjectDocs:
    file: lib/CatalystX/Usul/ProjectDocs.pm
    version: v0.8.1319
  CatalystX::Usul::QueryRequest:
    file: lib/CatalystX/Usul/QueryRequest.pm
    version: v0.8.1320
  CatalystX::Usul::Response::FileSystem:
    file: lib/CatalystX/Usul/Response/FileSystem.pm
    version: v0.1.1319
  CatalystX::Usul::Response::Users:
    file: lib/CatalystX/Usul/Response/Users.pm
    version: v0.1.1320
  CatalystX::Usul::Roles:
    file: lib/CatalystX/Usul/Roles.pm
    version: v0.8.1320
  CatalystX::Usul::Roles::DBIC:
    file: lib/CatalystX/Usul/Roles/DBIC.pm
    version: v0.8.1319
  CatalystX::Usul::Roles::Simple:
    file: lib/CatalystX/Usul/Roles/Simple.pm
    version: v0.8.1319
  CatalystX::Usul::Roles::Unix:
    file: lib/CatalystX/Usul/Roles/Unix.pm
    version: v0.8.1319
  CatalystX::Usul::Schema:
    file: lib/CatalystX/Usul/Schema.pm
    version: v0.8.1320
  CatalystX::Usul::Shells:
    file: lib/CatalystX/Usul/Shells.pm
    version: v0.8.1319
  CatalystX::Usul::TapeBackup:
    file: lib/CatalystX/Usul/TapeBackup.pm
    version: v0.8.1320
  CatalystX::Usul::TraitFor::BuildingUsul:
    file: lib/CatalystX/Usul/TraitFor/BuildingUsul.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Captcha:
    file: lib/CatalystX/Usul/TraitFor/Captcha.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::ConnectInfo:
    file: lib/CatalystX/Usul/TraitFor/ConnectInfo.pm
    version: v0.8.1320
  CatalystX::Usul::TraitFor::Controller::Cookies:
    file: lib/CatalystX/Usul/TraitFor/Controller/Cookies.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Controller::ModelHelper:
    file: lib/CatalystX/Usul/TraitFor/Controller/ModelHelper.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Controller::PersistentState:
    file: lib/CatalystX/Usul/TraitFor/Controller/PersistentState.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Controller::TokenValidation:
    file: lib/CatalystX/Usul/TraitFor/Controller/TokenValidation.pm
    version: v0.8.1305
  CatalystX::Usul::TraitFor::CreatingUsul:
    file: lib/CatalystX/Usul/TraitFor/CreatingUsul.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Email:
    file: lib/CatalystX/Usul/TraitFor/Email.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Engine::DumpInfo:
    file: lib/CatalystX/Usul/TraitFor/Engine/DumpInfo.pm
    version: v0.8.1305
  CatalystX::Usul::TraitFor::ListSessions:
    file: lib/CatalystX/Usul/TraitFor/ListSessions.pm
    version: v0.8.1305
  CatalystX::Usul::TraitFor::LogRequest:
    file: lib/CatalystX/Usul/TraitFor/LogRequest.pm
    version: v0.8.1319
  CatalystX::Usul::TraitFor::Model::NavigationLinks:
    file: lib/CatalystX/Usul/TraitFor/Model/NavigationLinks.pm
    version: v0.1.1319
  CatalystX::Usul::TraitFor::Model::QueryingRequest:
    file: lib/CatalystX/Usul/TraitFor/Model/QueryingRequest.pm
    version: v0.1.1305
  CatalystX::Usul::TraitFor::Model::StashHelper:
    file: lib/CatalystX/Usul/TraitFor/Model/StashHelper.pm
    version: v0.8.1320
  CatalystX::Usul::TraitFor::PostInstallConfig:
    file: lib/CatalystX/Usul/TraitFor/PostInstallConfig.pm
    version: v0.1.1320
  CatalystX::Usul::UserProfiles:
    file: lib/CatalystX/Usul/UserProfiles.pm
    version: v0.8.1319
  CatalystX::Usul::Users:
    file: lib/CatalystX/Usul/Users.pm
    version: v0.8.1320
  CatalystX::Usul::Users::DBIC:
    file: lib/CatalystX/Usul/Users/DBIC.pm
    version: v0.8.1320
  CatalystX::Usul::Users::Simple:
    file: lib/CatalystX/Usul/Users/Simple.pm
    version: v0.8.1319
  CatalystX::Usul::Users::Unix:
    file: lib/CatalystX/Usul/Users/Unix.pm
    version: v0.8.1320
  CatalystX::Usul::Users::UnixAdmin:
    file: lib/CatalystX/Usul/Users/UnixAdmin.pm
    version: v0.8.1320
  CatalystX::Usul::View:
    file: lib/CatalystX/Usul/View.pm
    version: v0.8.1320
  CatalystX::Usul::View::HTML:
    file: lib/CatalystX/Usul/View/HTML.pm
    version: v0.8.1319
  CatalystX::Usul::View::JSON:
    file: lib/CatalystX/Usul/View/JSON.pm
    version: v0.8.1319
  CatalystX::Usul::View::Serializer:
    file: lib/CatalystX/Usul/View/Serializer.pm
    version: v0.8.1319
  CatalystX::Usul::View::XML:
    file: lib/CatalystX/Usul/View/XML.pm
    version: v0.8.1319
recommends:
  App::cpanminus: 1.6005
  Crypt::PassGen: 0.05
  GD::SecurityImage: 1.7
  IPC::Run: 0.84
  Pod::ProjectDocs: 0.36
  Syntax::Highlight::Perl: 1
requires:
  Catalyst: 5.9002
  Catalyst::Action::RenderView: 0.16
  Catalyst::Model::DBIC::Schema: 0.48
  Catalyst::Plugin::Authentication: 0.10016
  Catalyst::Plugin::ConfigComponents: v0.6.0
  Catalyst::Plugin::ConfigLoader: 0.19
  Catalyst::Plugin::InflateMore: v0.5.0
  Catalyst::Plugin::Session: 0.31
  Catalyst::Plugin::Session::State::Cookie: 0.17
  Catalyst::Plugin::Session::Store::FastMmap: 0.14
  Catalyst::Plugin::Static::Simple: 0.3
  Catalyst::Plugin::StatusMessage: 1.002
  Catalyst::View::TT: 0.36
  CatalystX::Component::Traits: 0.16
  Class::Null: 2.10142
  Class::Usul: v0.21.3
  Crypt::Eksblowfish: 0.009
  DBIx::Class: 0.08009
  Data::Pageset: 1.06
  Data::Serializer: 0.53
  Data::Validation: v0.10.0
  Email::MIME: 1.906
  Email::Sender: 0.09338
  Encode: 2.12
  Encode::Guess: 2
  File::DataClass: v0.20.10
  File::Gettext: v0.18.0
  File::MailAlias: v0.16.0
  File::UnixAuth: v0.16.0
  HTML::FillInForm: 2
  HTML::FormWidgets: v0.18.0
  HTML::Parser: 3.69
  HTTP::Date: 6.02
  HTTP::Message: 6.06
  IO::Interactive: v0.0.6
  Imager: 0.9
  JSON: 2.5
  MIME::Types: 1.31
  Moo: 1.002
  MooX::Options: 3.83
  Moose: 2.0802
  MooseX::AttributeShortcuts: 0.014
  MooseX::Types: 0.35
  MooseX::Types::LoadableClass: 0.008
  PPI: 1.215
  PPI::HTML: 1.08
  Parse::HTTP::UserAgent: 0.33
  SQL::Translator: 0.11016
  Sub::Exporter: 0.982
  Template: 2.22
  Time::Elapsed: 0.29
  TryCatch: 1.003
  XML::Simple: 2.18
  namespace::autoclean: 0.13
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-Usul
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.8.1321
