---
name: CatalystX-Usul
version: 0.1.426
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: A base class for Catalyst MVC components
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::MakeMaker: 6.42
  version: 0.74
requires:
  CPAN: 1.9301
  Cache::FastMmap: 1.09
  Carp: 1.04
  Catalyst: 5.71
  Catalyst::Engine::Apache: 1.11
  Catalyst::Model::DBIC::Schema: 0.2
  Catalyst::Plugin::Authentication: 0.10006
  Catalyst::Plugin::Captcha: 0.03
  Catalyst::Plugin::ConfigComponents: 0.1.12
  Catalyst::Plugin::ConfigLoader: 0.19
  Catalyst::Plugin::FillInForm: 0.06
  Catalyst::Plugin::InflateMore: 0.1.4
  Catalyst::Plugin::Log::Handler: 0.07
  Catalyst::Plugin::Session::State::Cookie: 0.09
  Catalyst::Plugin::Session::Store::FastMmap: 0.05
  Catalyst::Plugin::Static::Simple: 0.2
  Catalyst::View::TT: 0.26
  Class::Accessor::Grouped: 0.08002
  Class::C3: 0.19
  Crypt::CBC: 2.3
  Crypt::PassGen: 0.05
  Crypt::Twofish: 2.12
  DBIx::Class: 0.08009
  Data::Pageset: 1.03
  Data::Serializer: 0.46
  Data::Validation: 0.1.3
  Date::Format: 2.22
  DateTime::Format::Epoch: 0.11
  Digest::SHA1: 2.11
  Email::MIME: 1.861
  Email::MIME::Creator: 1.454
  Email::Send: 2.192
  Encode: 2.12
  Encode::Guess: 2
  Exception::Class: 1.23
  File::Find: 1.1
  File::Path: 2.07
  File::Remove: 0.34
  File::Temp: 0.2
  Getopt::Mixed: 1.008
  HTML::Accessors: 0.1.3
  HTML::FormWidgets: 0.3.126
  HTTP::Headers::Util: 1.13
  Hash::Merge: 0.08
  IO::Dir: 1.06
  IO::File: 1.14
  IO::Interactive: 0.0.3
  IPC::Open3: 1.02
  IPC::SRLock: 0.1.34
  IPC::SysV: 1.04
  Imager: 0.65
  JSON: 2.12
  Lingua::EN::NameParse: 1.24
  Lingua::Flags: 0.04
  Log::Handler: 0.11
  MIME::Types: 1.23
  Module::Build: 0.2805
  Module::Pluggable::Object: 3.6
  POSIX: 1.09
  Path::Class: 0.16
  Pod::ProjectDocs: 0.36
  Proc::ProcessTable: 0.4
  SQL::Translator: 0.08
  Template: 2.18
  Term::ReadKey: 2.3
  Text::Autoformat: 1.13
  Text::Markdown: 1.0.20
  Text::Tabs: 2005.0824
  Time::Elapsed: 0.1
  Time::Zone: 2.22
  Unix::GroupFile: 0.06
  XML::Bare: 0.3
  XML::Simple: 2.14
  YAML::Syck: 1.05
  parent: 0.221
  perl: 5.008
  version: 0.74
build_requires:
  Exception::Class: 1.23
  Test::Harness: 2.64
  Test::More: 0.74
  Test::Pod: 1.14
recommends:
  Catalyst::Engine::HTTP::Prefork: 0.01
  Syntax::Highlight::Perl: 1
provides:
  CatalystX::Usul:
    file: lib/CatalystX/Usul.pm
    version: 0.1.426
  CatalystX::Usul::Action:
    file: lib/CatalystX/Usul/Action.pm
    version: 0.1.416
  CatalystX::Usul::Authentication:
    file: lib/CatalystX/Usul/Authentication.pm
    version: 0.1.402
  CatalystX::Usul::Base:
    file: lib/CatalystX/Usul/Base.pm
    version: 0.1.424
  CatalystX::Usul::Build:
    file: lib/CatalystX/Usul/Build.pm
    version: 0.1.402
  CatalystX::Usul::Controller:
    file: lib/CatalystX/Usul/Controller.pm
    version: 0.1.402
  CatalystX::Usul::Controller::Admin:
    file: lib/CatalystX/Usul/Controller/Admin.pm
    version: 0.1.402
  CatalystX::Usul::Controller::Admin::Backup:
    file: lib/CatalystX/Usul/Controller/Admin/Backup.pm
    version: 0.1.422
  CatalystX::Usul::Controller::Admin::Config:
    file: lib/CatalystX/Usul/Controller/Admin/Config.pm
    version: 0.1.406
  CatalystX::Usul::Controller::Admin::Locks:
    file: lib/CatalystX/Usul/Controller/Admin/Locks.pm
    version: 0.1.395
  CatalystX::Usul::Controller::Admin::Navigation:
    file: lib/CatalystX/Usul/Controller/Admin/Navigation.pm
    version: 0.1.406
  CatalystX::Usul::Controller::Admin::Processes:
    file: lib/CatalystX/Usul/Controller/Admin/Processes.pm
    version: 0.1.401
  CatalystX::Usul::Controller::Admin::RoleManager:
    file: lib/CatalystX/Usul/Controller/Admin/RoleManager.pm
    version: 0.1.401
  CatalystX::Usul::Controller::Admin::UserManager:
    file: lib/CatalystX/Usul/Controller/Admin/UserManager.pm
    version: 0.1.406
  CatalystX::Usul::Controller::Entrance:
    file: lib/CatalystX/Usul/Controller/Entrance.pm
    version: 0.1.406
  CatalystX::Usul::Controller::Root:
    file: lib/CatalystX/Usul/Controller/Root.pm
    version: 0.1.402
  CatalystX::Usul::Encoding:
    file: lib/CatalystX/Usul/Encoding.pm
    version: 0.1.402
  CatalystX::Usul::Exception:
    file: lib/CatalystX/Usul/Exception.pm
    version: 0.1.402
  CatalystX::Usul::File:
    file: lib/CatalystX/Usul/File.pm
    version: 0.1.407
  CatalystX::Usul::File::Element:
    file: lib/CatalystX/Usul/File/Element.pm
    version: 0.1.402
  CatalystX::Usul::File::IO:
    file: lib/CatalystX/Usul/File/IO.pm
    version: 0.1.379
  CatalystX::Usul::File::List:
    file: lib/CatalystX/Usul/File/List.pm
    version: 0.1.402
  CatalystX::Usul::File::ResultSet:
    file: lib/CatalystX/Usul/File/ResultSet.pm
    version: 0.1.402
  CatalystX::Usul::File::ResultSource:
    file: lib/CatalystX/Usul/File/ResultSource.pm
    version: 0.1.402
  CatalystX::Usul::File::Schema:
    file: lib/CatalystX/Usul/File/Schema.pm
    version: 0.1.402
  CatalystX::Usul::File::Storage:
    file: lib/CatalystX/Usul/File/Storage.pm
    version: 0.1.402
  CatalystX::Usul::File::Storage::XML:
    file: lib/CatalystX/Usul/File/Storage/XML.pm
    version: 0.1.407
  CatalystX::Usul::File::Storage::XML::Bare:
    file: lib/CatalystX/Usul/File/Storage/XML/Bare.pm
    version: 0.1.402
  CatalystX::Usul::File::Storage::XML::Simple:
    file: lib/CatalystX/Usul/File/Storage/XML/Simple.pm
    version: 0.1.402
  CatalystX::Usul::FileSystem:
    file: lib/CatalystX/Usul/FileSystem.pm
    version: 0.1.402
  CatalystX::Usul::InflateSymbols:
    file: lib/CatalystX/Usul/InflateSymbols.pm
    version: 0.1.402
  CatalystX::Usul::MailAliases:
    file: lib/CatalystX/Usul/MailAliases.pm
    version: 0.1.372
  CatalystX::Usul::Model:
    file: lib/CatalystX/Usul/Model.pm
    version: 0.1.402
  CatalystX::Usul::Model::Config:
    file: lib/CatalystX/Usul/Model/Config.pm
    version: 0.1.424
  CatalystX::Usul::Model::Config::Buttons:
    file: lib/CatalystX/Usul/Model/Config/Buttons.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Credentials:
    file: lib/CatalystX/Usul/Model/Config/Credentials.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Fields:
    file: lib/CatalystX/Usul/Model/Config/Fields.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Globals:
    file: lib/CatalystX/Usul/Model/Config/Globals.pm
    version: 0.1.406
  CatalystX::Usul::Model::Config::Keys:
    file: lib/CatalystX/Usul/Model/Config/Keys.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Levels:
    file: lib/CatalystX/Usul/Model/Config/Levels.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Messages:
    file: lib/CatalystX/Usul/Model/Config/Messages.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Pages:
    file: lib/CatalystX/Usul/Model/Config/Pages.pm
    version: 0.1.401
  CatalystX::Usul::Model::Config::Rooms:
    file: lib/CatalystX/Usul/Model/Config/Rooms.pm
    version: 0.1.406
  CatalystX::Usul::Model::FileSystem:
    file: lib/CatalystX/Usul/Model/FileSystem.pm
    version: 0.1.402
  CatalystX::Usul::Model::Help:
    file: lib/CatalystX/Usul/Model/Help.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity:
    file: lib/CatalystX/Usul/Model/Identity.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity::Roles:
    file: lib/CatalystX/Usul/Model/Identity/Roles.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity::Roles::DBIC:
    file: lib/CatalystX/Usul/Model/Identity/Roles/DBIC.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity::Roles::Unix:
    file: lib/CatalystX/Usul/Model/Identity/Roles/Unix.pm
    version: 0.1.425
  CatalystX::Usul::Model::Identity::Suid:
    file: lib/CatalystX/Usul/Model/Identity/Suid.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity::Users:
    file: lib/CatalystX/Usul/Model/Identity/Users.pm
    version: 0.1.424
  CatalystX::Usul::Model::Identity::Users::DBIC:
    file: lib/CatalystX/Usul/Model/Identity/Users/DBIC.pm
    version: 0.1.402
  CatalystX::Usul::Model::Identity::Users::Unix:
    file: lib/CatalystX/Usul/Model/Identity/Users/Unix.pm
    version: 0.1.402
  CatalystX::Usul::Model::Imager:
    file: lib/CatalystX/Usul/Model/Imager.pm
    version: 0.1.402
  CatalystX::Usul::Model::MailAliases:
    file: lib/CatalystX/Usul/Model/MailAliases.pm
    version: 0.1.395
  CatalystX::Usul::Model::Navigation:
    file: lib/CatalystX/Usul/Model/Navigation.pm
    version: 0.1.402
  CatalystX::Usul::Model::Process:
    file: lib/CatalystX/Usul/Model/Process.pm
    version: 0.1.402
  CatalystX::Usul::Model::Schema:
    file: lib/CatalystX/Usul/Model/Schema.pm
    version: 0.1.372
  CatalystX::Usul::Model::Session:
    file: lib/CatalystX/Usul/Model/Session.pm
    version: 0.1.402
  CatalystX::Usul::Model::Tapes:
    file: lib/CatalystX/Usul/Model/Tapes.pm
    version: 0.1.402
  CatalystX::Usul::Model::UserProfiles:
    file: lib/CatalystX/Usul/Model/UserProfiles.pm
    version: 0.1.408
  CatalystX::Usul::PersistentState:
    file: lib/CatalystX/Usul/PersistentState.pm
    version: 0.1.403
  CatalystX::Usul::Plugin::Controller::Cookies:
    file: lib/CatalystX/Usul/Plugin/Controller/Cookies.pm
    version: 0.1.425
  CatalystX::Usul::Plugin::Controller::ModelHelper:
    file: lib/CatalystX/Usul/Plugin/Controller/ModelHelper.pm
    version: 0.1.425
  CatalystX::Usul::Plugin::Controller::TokenValidation:
    file: lib/CatalystX/Usul/Plugin/Controller/TokenValidation.pm
    version: 0.1.403
  CatalystX::Usul::Plugin::Model::StashHelper:
    file: lib/CatalystX/Usul/Plugin/Model/StashHelper.pm
    version: 0.1.406
  CatalystX::Usul::Process:
    file: lib/CatalystX/Usul/Process.pm
    version: 0.1.403
  CatalystX::Usul::Programs:
    file: lib/CatalystX/Usul/Programs.pm
    version: 0.1.419
  CatalystX::Usul::ProjectDocs:
    file: lib/CatalystX/Usul/ProjectDocs.pm
    version: 0.1.403
  CatalystX::Usul::Response:
    file: lib/CatalystX/Usul/Response.pm
    version: 0.1.403
  CatalystX::Usul::Schema:
    file: lib/CatalystX/Usul/Schema.pm
    version: 0.1.403
  CatalystX::Usul::Shells:
    file: lib/CatalystX/Usul/Shells.pm
    version: 0.1.367
  CatalystX::Usul::Table:
    file: lib/CatalystX/Usul/Table.pm
    version: 0.1.403
  CatalystX::Usul::TapeDevice:
    file: lib/CatalystX/Usul/TapeDevice.pm
    version: 0.1.403
  CatalystX::Usul::Time:
    file: lib/CatalystX/Usul/Time.pm
    version: 0.1.347
  CatalystX::Usul::Utils:
    file: lib/CatalystX/Usul/Utils.pm
    version: 0.1.425
  CatalystX::Usul::View:
    file: lib/CatalystX/Usul/View.pm
    version: 0.1.404
  CatalystX::Usul::View::HTML:
    file: lib/CatalystX/Usul/View/HTML.pm
    version: 0.1.403
  CatalystX::Usul::View::JSON:
    file: lib/CatalystX/Usul/View/JSON.pm
    version: 0.1.330
  CatalystX::Usul::View::Serializer:
    file: lib/CatalystX/Usul/View/Serializer.pm
    version: 0.1.403
  CatalystX::Usul::View::XML:
    file: lib/CatalystX/Usul/View/XML.pm
    version: 0.1.334
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
